### ISSUE TITLE
./startFabric.sh command is not able to run my container can somebody help me 

### ISSUE THREAD

**Issue by UmarMaqbool** [IBM/Decentralized-Energy-Composer#34]
![capture](https://user-images.githubusercontent.com/28223363/47087135-b153ed80-d234-11e8-8706-fe9f27b5c7eb.JPG)

**Comment by ljbennett62** [comment]
@UmarMaqbool - try setting the FABRIC_VERSION to hlfv11. It works with that version of hyperledger -we are in teh midst of updating this pattern from using the Composer API to the Fabric SDK.

**Comment by ljbennett62** [comment]
@UmarMaqbool - the pattern was just upgrade to v1.2. Please try again and follow instructions very closely - I went through and was able to do successfully.

**Comment by ljbennett62** [comment]
@UmarMaqbool - see the response from issue #7 `Hi! When running startFabric.sh, I had the same problem with a container that was not running. For example : Error response from daemon: Container 43f2bcdc71066896bec4189728375977ec5e1cfe77472096a6fab22be8527cfb is not running To SOLVE this : in the file fabric-tools/hlfv12/ (because images was already installed, otherwise I think hlfv1 will run startFabric.sh) I comment the following line in the startFabric.sh script : docker-compose -f "${DOCKER_FILE}" down so that we keep the dockers already installed when running again startFabric.sh (and so the following command won't be useless) , then I start the not-running container : docker start 43f2bcdc71066896bec4189728375977ec5e1cfe77472096a6fab22be8527cfb and finally, run ./startFabric.sh and all goes right since we have all dockers we need. Hope it will do the trick for you` This seemed to resolve another person's problem.
