### ISSUE TITLE
Error while running ./startFabric.sh in WSL

### ISSUE THREAD

**Issue by Jhaankit5487** [IBM/Decentralized-Energy-Composer#36]
Upon running ./startFabric.sh on WSL, I get the error **SSL error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)**.

**Comment by animeshmdhokare** [comment]
I am having the same problem ...
![2018-11-22 01_42_26-animesh desktop-j62ulp6_ _fabric-dev-servers](https://user-images.githubusercontent.com/19922659/48866205-08328100-edf8-11e8-8c0e-c912f0784226.png)

**Comment by ljbennett62** [comment]
@animeshmdhokare @Jhaankit5487 - I think you are going to have to set the FABRIC_VERSION to hlfv11.  It works with that version: FABRIC_VERSION is unset, assuming hlfv11. BTW - we will update this to use Fabric SDK over the Composer APIs.

**Comment by ljbennett62** [comment]
@animeshmdhokare @Jhaankit5487 - the pattern has been updated to 1.2. - please try the pattern again following the instructions closely.  I just went through it again and it works fine.

**Comment by drantonisk** [comment]
Upon running ./stopFabric.sh and ./teardownFabric.sh  I get the error ERROR: error while removing network: network composer_default id 9e3c9b3ada7898ef6b03f4024d9bf20b2bb52f28f0f8693423fe42d25d6012d4 has active endpoints

**Comment by ljbennett62** [comment]
@animeshmdhokare - see the response from issue #7 `Hi! When running startFabric.sh, I had the same problem with a container that was not running. For example :
Error response from daemon: Container 43f2bcdc71066896bec4189728375977ec5e1cfe77472096a6fab22be8527cfb is not running
To SOLVE this : in the file fabric-tools/hlfv12/ (because images was already installed, otherwise I think hlfv1 will run startFabric.sh) I comment the following line in the startFabric.sh script :
docker-compose -f "${DOCKER_FILE}" down
so that we keep the dockers already installed when running again startFabric.sh (and so the following command won't be useless) , then I start the not-running container :
docker start 43f2bcdc71066896bec4189728375977ec5e1cfe77472096a6fab22be8527cfb
and finally, run ./startFabric.sh and all goes right since we have all dockers we need.
Hope it will do the trick for you`   This seemed to resolve another person's problem.
