### ISSUE TITLE
Error in ./startFabric.sh

### ISSUE THREAD

**Issue by mna2016** [IBM/Decentralized-Energy-Composer#7]
the startFabric.sh script has the following errors:

# Create the channel
docker exec peer0.org1.example.com peer channel create -o orderer.example.com:70
50 -c composerchannel -f /etc/hyperledger/configtx/composer-channel.tx
Error response from daemon: Container 8a2603a405ed625b689f960bc81afa3269b54664ff
f15a587dc12cac6007c21c is not running

**Comment by raheelzubairy** [comment]
@mna2016 appears to be issue with docker container.  Have you tried removing docker containers and then running the script?

**Comment by herrsergio** [comment]
I had the same issue and the problem was that I had a directory with root as the owner.

**Comment by bjfderuiter** [comment]
I have the same issue. I run it as user from my own user folder. 

## command
docker exec peer0.org1.example.com peer channel create -o orderer.example.com:7050 -c composerchannel -f /etc/hyperledger/configtx/composer-channel.tx

## error
Error response from daemon: Container 2f57fa8ac686886b42a746e606028e11e4c89eb64d50ff9193fe1bff8215a494 is not running 

## Setup
Ubuntu 16.04 lts. Softlayer VM

**Comment by jpradier** [comment]
I have the same issue.
Following the steps from the blockchain developer-tutorial at https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial.html

My startFabric.sh fails with 
Error response from daemon: Container d2a4df08857333ddc46026fe26376af58116af8d39af2823e222aeebedddb648 is not running

ibm@pradi0514075029:~/fabric-dev-servers$ docker ps -a
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS                         PORTS                                        NAMES
d2a4df088573        hyperledger/fabric-peer:x86_64-1.1.0      "peer node start"        About an hour ago Exited (2) About an hour ago                                                peer0.org1.example.com
0f690b2a6629        hyperledger/fabric-couchdb:x86_64-0.4.6   "tini -- /docker-ent…"   About an hour ago   Up About an hour               4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp   couchdb
8cde7086fd80        hyperledger/fabric-ca:x86_64-1.1.0        "sh -c 'fabric-ca-se…"   About an hour ago   Up About an hour               0.0.0.0:7054->7054/tcp                       ca.org1.example.com
4e9dd5b6d33f        hyperledger/fabric-orderer:x86_64-1.1.0   "orderer"                About an hour ago   Up About an hour               0.0.0.0:7050->7050/tcp                       orderer.example.com

It seems to day that my peer container has exited.
I am on Ubuntu 16.04.3 LTS (xenial).

**Comment by vanishtachangea** [comment]
Hi, 
Has anyone found a solution to this problem when running ./startFabric.sh, getting the error: 
Error response from daemon: Container 43f2bcdc71066896bec4189728375977ec5e1cfe77472096a6fab22be8527cfb is not running

**Comment by varunagarwal315** [comment]
Can you mention the exact steps you follow to re-create the error.

**Comment by vanishtachangea** [comment]
I have reinstalled the CLI tool, the hyperledger fabric as per :+1: 
https://hyperledger.github.io/composer/latest/installing/installing-prereqs
https://hyperledger.github.io/composer/latest/installing/development-tools

I deleted the containers and try to run ./startFabric.sh, I'm getting this error. But I started getting the error before itself, that's why I did the uninstall and reinstall when nothing was fixing it.  Now, I'm checking the docker side.. 

If anyone has been able to fix this, please let me know.

**Comment by thib00** [comment]
Hi! When running startFabric.sh, I had the same problem with a container that was not running. For example : 
Error response from daemon: Container 43f2bcdc71066896bec4189728375977ec5e1cfe77472096a6fab22be8527cfb is not running
To SOLVE this : in the file fabric-tools/hlfv12/ (because images was already installed, otherwise I think hlfv1 will run startFabric.sh) I comment the following line in the startFabric.sh script : 
docker-compose -f "${DOCKER_FILE}" down
so that we keep the dockers already installed when running again startFabric.sh (and so the following command won't be useless) , then I start the not-running container : 
docker start 43f2bcdc71066896bec4189728375977ec5e1cfe77472096a6fab22be8527cfb
and finally, run ./startFabric.sh and all goes right since we have all dockers we need.
Hope it will do the trick for you

**Comment by vanishtachangea** [comment]
Thanks @thib00  God Bless you! It worked!

**Comment by leonardomgt** [comment]
> Hi! When running startFabric.sh, I had the same problem with a container that was not running. For example :
> Error response from daemon: Container 43f2bcdc71066896bec4189728375977ec5e1cfe77472096a6fab22be8527cfb is not running
> To SOLVE this : in the file fabric-tools/hlfv12/ (because images was already installed, otherwise I think hlfv1 will run startFabric.sh) I comment the following line in the startFabric.sh script :
> docker-compose -f "${DOCKER_FILE}" down
> so that we keep the dockers already installed when running again startFabric.sh (and so the following command won't be useless) , then I start the not-running container :
> docker start 43f2bcdc71066896bec4189728375977ec5e1cfe77472096a6fab22be8527cfb
> and finally, run ./startFabric.sh and all goes right since we have all dockers we need.
> Hope it will do the trick for you

I had the same issue and I tried that. When I run `docker start <contianerID>` it works and the container goes up, but a few seconds later, the container goes down again, I don't know how nor why. Does someone have any idea why this happens and how to solve it?
